version: "3.8"

services:
  mysqldb:
    image: mysql:latest
    restart: unless-stopped
    ports:
      - 3307:3306
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=devops
      - MYSQL_USER=root
      - MYSQL_PASSWORD=your_new_password

  DevOps_Project-backend:
    depends_on:
      - mysqldb
    build: ./
    restart: on-failure
    ports:
      - 8082:8082
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
    image: medslama21/devopsproject:1.0
  angular-frontend: # Add this new service
    build:
      context: ../DevOps_Project_Front  # Use the correct path to your Angular project
      dockerfile: Dockerfile  # Use the Dockerfile you created
    ports:
      - 80:80
volumes:
  db:
  .m2:
